apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: nginx-container
    image: debian
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        port: 80
        path: /
